
days = ["Thursday 22 (Foyer du Lac)", "Thursday 22 (Bruyère)", "Friday 23 (Foyer du Lac)", "Friday 23 (Bruyère)"]

[talks]

[talks.1_08_30]
title = "Coffee and registration"
type = "organization"

[talks.1_09_30]
title = "Invited talks"

[talks.1_10_30]
title = "Morning tea"
type = "break"

[talks.1_11_00]
title = "Contributed talks"

[talks.1_12_30]
title = "Lunch"
type = "break"

[talks.1_14_00]
title = "Contributed talks"

[talks.1_15_30]
title = "Afternoon tea"
type = "break"

[talks.1_16_00]
title = "Invited talks"

[talks.1_17_00]
title = "Dinner"
type = "organization"


[talks.2_08_30]
type = "organization"

[talks.2_10_30]
type = "break"

[talks.2_11_00]
title = "Contributed talks"

[talks.2_12_30]
type = "break"

[talks.2_14_00]
title = "Contributed talks"

[talks.2_15_30]
type = "break"

[talks.2_17_00]
type = "organization"


[talks.3_08_30]
type = "organization"

[talks.3_09_30]
title = "Invited talks"

[talks.3_10_30]
title = "Morning tea"
type = "break"

[talks.3_11_00]
title = "Contributed talks"

[talks.3_12_30]
title = "Lunch"
type = "break"

[talks.3_14_00]
title = "Contributed talks"

[talks.3_15_30]
title = "Afternoon tea"
type = "break"

[talks.3_16_00]
title = "Invited talks"

[talks.3_16_45]
title = "Prizegiving"

[talks.3_17_00]
title = "Workshop finishes"
type = "organization"


[talks.4_08_30]
type = "organization"

[talks.4_10_30]
type = "break"

[talks.4_11_00]
title = "Contributed talks"

[talks.4_12_30]
title = "Lunch"
type = "break"

[talks.4_14_00]
title = "Contributed talks"

[talks.4_15_30]
type = "break"

[talks.4_17_00]
type = "organization"
