
days = ["Sunday 31 (Prestonfield)", "Monday 1 (Prestonfield)", " Monday 1 (Holyrood)"]

[talks]

[talks.1_08_30]
title = "Coffee"
type = "organization"

[talks.1_09_00]
type = "organization"

[talks.1_09_15]
title = "Introduction and welcome"
speaker = "Oscar Dowson"

[talks.1_09_30]
title = "ElectricityEmissions.jl: Calculating carbon intensity signals on the power grid"
speaker = "Noah Rhodes"
slides = "slides_noah.pdf"
url = "https://youtu.be/fmvyd0OoKWw"

[talks.1_09_45]
title = "Optimal Planning for Steel Industry Decarbonization: A Mixed-Integer Linear Programming Approach in Julia"
speaker = "Vinícius Justen Pinto"
slides = "slides_vinicius.pdf"
url = "https://youtu.be/tq_I3iNWW88"

[talks.1_10_00]
title = "Optimize Your Fleet with Odoo and JuMP"
speaker = "Benoît Legat"
slides = "slides_benoit.pdf"
url = "https://youtu.be/hxph7NR6JeM"

[talks.1_10_15]
title = "DuckDB as backend to build optimization models in JuMP.jl"
speaker = "Abel Siqueira"
slides = "slides_abel.pdf"
url = "https://youtu.be/8mmYRna_c-U"

[talks.1_10_30]
title = "Morning tea"
type = "break"

[talks.1_10_45]
type = "break"

[talks.1_11_00]
title = "UnoSolver.jl, a unified SQP/barrier solver for nonlinearly constrained optimization"
speaker = "Charlie Vanaret"
slides = "slides_charlie.pdf"
url = "https://youtu.be/hDPCVBQm8TE"

[talks.1_11_15]

[talks.1_11_30]
title = "Reduced-space nonlinear optimization via the implicit function theorem"
speaker = "Robert Parker"
url = "https://youtu.be/lz4Xj_V47nM"

[talks.1_11_45]

[talks.1_12_00]
title = "Batched optimization solvers: a tour d'horizon"
speaker = "François Pacaud"
url = "https://youtu.be/dU0-UpvWK6Q"

[talks.1_12_30]
title = "Lunch (provided on-site)"
type = "break"

[talks.1_14_00]
type = "break"

[talks.1_14_15]
title = "Antipode JuMPing - How Norwegian authorities can use JADE.jl for better decision making"
speaker = "Jarand Hole"
url = "https://youtu.be/dGgAxpKQoQ4"

[talks.1_14_30]
title = "Automatic Decomposition of JuMP Models using TimeStructDecomposition.jl"
speaker = "Truls Flatberg"
slides = "slides_truls.pdf"
url = "https://youtu.be/hcOkx8W9C1k"

[talks.1_14_45]
title = "Advanced Model Composition in ApplicationDrivenLearning.jl"
speaker = "Giovanni Amorim"
slides = "slides_giovanni.pdf"
url = "https://youtu.be/pFW62ID4Nuw"

[talks.1_15_00]
title = "Modelling and Solving Mathematical Programs with Complementarity Constraints."
speaker = "Anton Edvinovich Pozharskiy"
slides = "slides_anton.pdf"

[talks.1_15_15]
title = "Adding array support for JuMP’s Automatic Differentiation"
speaker = "Sophie Lequeu"
slides = "slides_sophie.pdf"

[talks.1_15_30]
title = "Afternoon tea"
type = "break"

[talks.1_15_45]
type = "break"

[talks.1_16_00]
title = "Can ExaModels Power JuMP on GPUs?"
speaker = "Sungho Shin"

[talks.1_16_15]
title = "JuMP's macros: why are they needed?"
speaker = "Oscar Dowson"
slides = "slides_oscar.pdf"

[talks.1_16_30]

[talks.1_16_45]

[talks.1_17_00]
title = "Dinner"
type = "organization"

[talks.2_08_30]
title = "Coffee"
type = "organization"

[talks.2_09_00]
type = "organization"

[talks.2_09_15]
type = "organization"

[talks.2_09_30]
title = "DiffOpt.jl: Differentiable optimization for JuMP"
speaker = "Joaquim Dias Garcia"
slides = "slides_joaquim.pdf"

[talks.2_09_45]

[talks.2_10_00]
title = "DisjunctiveProgramming.jl’s New Suite of Solution Methods"
speaker = "Daniel Nguyen"
slides = "slides_daniel.pdf"

[talks.2_10_15]
title = "DisjunctiveNet.jl: Neural Symbolic Learning via Differentiable Convexified Optimization Layers"
speaker = "Can Li"
slides = "slides_can.pdf"

[talks.2_10_30]
title = "Morning tea"
type = "break"

[talks.2_10_45]
type = "break"

[talks.2_11_00]
title = "Encoding Matters when Embedding NNs in Optimization Problems"
speaker = "Chelsea Sidrane"

[talks.2_11_15]
title = "InfiniteMathOptAI.jl: Embedding Surrogates for Infinite-Dimensional Optimization"
speaker = "Joshua Pulsipher"
slides = "slides_josh.pdf"

[talks.2_11_30]
title = "Optimization Problem Surrogates with Graph Transformer Networks and integration within simulation workflows"
speaker = "Jose Daniel Lara"

[talks.2_12_00]
title = "Toward Extending EAGO.jl for Exploiting GPU Parallelism"
speaker = "Dimitri Alston"
slides = "slides_dimitri.pdf"

[talks.2_12_15]

[talks.2_12_30]
title = "Lunch (provided on-site)"
type = "break"

[talks.2_14_00]
title = "Second-Order GPU solver for Burer-Monteiro"
speaker = "Benoît Legat"
slides = "slides_benoit_gpu.html"

[talks.2_14_15]
title = "GraphsOfConvexSets.jl: Optimisation over Graphs of Convex Sets with JuMP"
speaker = "Charles van Hees"
slides = "slides_charles.pdf"

[talks.2_14_30]
title = "First-order Convex (mixed-integer) optimization: FrankWolfe.jl and Boscia.jl"
speaker = "Deborah Hendrych"
slides = "slides_deborah.pdf"

[talks.2_14_45]
title = "TenSolver.jl: A tensor network based QUBO solver with JuMP integration"
speaker = "Iago Leal de Freitas"
slides = "slides_iago.pdf"

[talks.2_15_00]
title = "PEPit.jl: Computer-Assisted Worst-Case Analysis of First-Order Optimization Algorithms in Julia"
speaker = "Shuvomoy Das Gupta"
slides = "slides_shuvomoy.pdf"

[talks.2_15_30]
title = "Afternoon tea"
type = "break"

[talks.2_15_45]
type = "break"

[talks.2_16_00]
type = "break"

[talks.2_16_15]
title = "The 2026 JuMP-dev prize"
speaker = "The JuMP developers"

[talks.2_16_30]

[talks.2_16_45]

[talks.2_17_00]
type = "organization"
title = "Workshop ends"

[talks.3_08_30]
title = "Coffee"
type = "organization"

[talks.3_09_00]
type = "organization"

[talks.3_09_15]
type = "organization"

[talks.3_09_30]
speaker = "Julian Hall"
title = "What's new in HiGHS"

[talks.3_10_00]
speaker = "Yanyu Zhou"
title = "HiPDLP: A PDLP solver for HiGHS"

[talks.3_10_30]
title = "Morning tea"
type = "break"

[talks.3_10_45]
type = "break"

[talks.3_11_00]
speaker = "Lucas Biton"
title = "Tallarium"

[talks.3_11_30]
speaker = "Soren Little"
title = "Prescriptive Analytics ought to be in the database"

[talks.3_11_45]

[talks.3_12_00]
speaker = "Ivona Gjeroska and Bárbara Cotrim Rodrigues"
title = "Optimisation Problems at Edinburgh Airport"

[talks.3_12_30]
title = "Lunch (provided on-site)"
type = "break"

[talks.3_14_00]
speaker = "Daniele Lerede"
title = "Open Energy Benchmark: 2025 results, HiPO performance, and call for benchmarks"

[talks.3_14_30]
speaker = "Filippo Zanetti"
title = "Recent developments and future plans for HiPO"

[talks.3_15_00]
speaker = "Mark Turner"
title = "A parallel MIP solver for HiGHS!"

[talks.3_15_30]
title = "Afternoon tea"
type = "break"

[talks.3_15_45]
type = "break"

[talks.3_16_00]
speaker = "Ben Champion"
title = "Local heuristics for the HiGHS MIP solver"

[talks.3_16_15]
type = "break"

[talks.3_16_30]
type = "break"

[talks.3_16_45]
type = "break"

[talks.3_17_00]
type = "organization"
title = "Workshop ends"
